# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  imageRepo: publicrepo
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'vivekdocker'
    #     repository: '$(imageRepo)'
    #     command: 'buildAndPush'
    #     Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'vigneshwarashoppingacr'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
          latest
    
